# Site settings
title: A Hoverbear's Musings
author: Andrew Hobden
email: andrew@hoverbear.org
description: >
    Articles primarily relating to science and technology.
url: "https://hoverbear.org"
baseurl: ""

# Media
cover: "/assets/images/cover.jpg"
logo: "/assets/images/logo.png"

# Build settings
paginate: 10
paginate_path: "/archive/:num"
markdown: kramdown
permalink: pretty
exclude: ["_drafts"]

kramdown:
  auto_ids: true
  math_engine: mathjax
  syntax_highlighter: rouge

# social icons and sharing options
twitter_username: andrewhobden
github_username: Hoverbear
