# Site settings
title: "Musings"
author: "Hoverbear"
email: "andrew@hoverbear.org"
description: >
    A collection of articles related to life and adventures in the open source community.
url: "https://hoverbear.org"
baseurl: ""

# Media
cover: "/assets/images/cover.jpg"
logo: "/assets/images/logo.png"

# Build settings
paginate: 5
paginate_path: "/archive/:num"
markdown: kramdown
permalink: pretty
exclude: ["_drafts"]

kramdown:
  auto_ids: true
  math_engine: mathjax
  syntax_highlighter: rouge

# social icons and sharing options
twitter_username: andrewhobden
github_username: Hoverbear
