# Site settings
title: "Musings"
author: "Ana Hobden"
email: "operator@hoverbear.org"
description: >
    Musings of an open source Distributed Systems engineer working remotely in western Canada.
url: "https://hoverbear.org"
baseurl: ""

# Media
cover: "/assets/images/cover.jpg"
logo: "/assets/images/logo.png"

# Build settings
paginate: 5
paginate_path: "/archive/:num"
markdown: kramdown
permalink: pretty
exclude: ["_drafts"]

kramdown:
  auto_ids: true
  math_engine: mathjax
  syntax_highlighter: rouge

# social icons and sharing options
twitter_username: a_hoverbear
github_username: Hoverbear
