# Site settings
title: A Hoverbear's Musings
email: andrew@hoverbear.org
description: > # this means to ignore newlines until "baseurl:"
  A collection of articles relating to life in Open Source development. Maintained by Andrew Hobden, an undergraduate student and (Mod)ularity Squad member at the University of Victoria.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hoverbear.org" # the base hostname & protocol for your site
twitter_username: andrewhobden
github_username:  hoverbear

# Build settings
markdown: kramdown
post_ext: markdown
page_ext: markdown
