# Site settings
title: A Hoverbear's Musings
author: Andrew Hobden
email: andrew@hoverbear.org
description: >
  A collection of articles relating to life in Open Source development. Maintained by Andrew Hobden, an undergraduate student and (Mod)ularity Squad member at the University of Victoria.
url: "http://hoverbear.org"
baseurl: ""

# Media
cover: "/assets/images/cover.jpg"
logo: "/assets/images/logo.png"

# Build settings
paginate: 10
paginate_path: "/archive/:num"
markdown: redcarpet
highlighter: rouge
permalink: pretty
exclude: ["_drafts"]
sass:
    style: compressed

# Tagging
tag_page_layout: tag
tag_page_dir: tag
tag_permalink_style: pretty

# social icons and sharing options
twitter_username: andrewhobden
github_username: Hoverbear
