# Site settings
title: A Hoverbear's Musings
email: andrew@hoverbear.org
description: >
  A collection of articles relating to life in Open Source development. Maintained by Andrew Hobden, an undergraduate student and (Mod)ularity Squad member at the University of Victoria.
baseurl: ""
url: "http://hoverbear.org"
twitter_username: andrewhobden
github_username:  hoverbear

# Build settings
markdown: redcarpet
permalink: pretty

# Octopress
post_ext: md
page_ext: md
