# Site settings
title: A Hoverbear's Musings
author: Andrew Hobden
email: andrew@hoverbear.org
description: >
  A collection of articles relating to life in Open Source development. Maintained by Andrew Hobden, an undergraduate student and (Mod)ularity Squad member at the University of Victoria.

# Media
cover: "/assets/cover.jpg"
logo: "/assets/logo.png"


url: "http://hoverbear.org"
baseurl: ""
paginate: 10

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty

# Octopress
post_ext: md
page_ext: md

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/andrewhobden
    desc:   Twitter
  - icon:	github
    url:	https://github.com/Hoverbear
    desc:	Github
