name = "hoverbear"
description = "A theme suited to a hovering bear."
license = "MIT"
homepage = "hoverbear.org"
min_version = "0.4.0"

[extra]

[author]
name = "Ana Hobden"
homepage = "hoverbear.org"