name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions-bot@users.noreply.github.com"
        git config --global url."https://".insteadOf git://
        git config --global url."https://github.com/".insteadOf "git@github.com:"
    - name: Fetch site
      run: |
        git init .
        git remote add origin https://github.com/Hoverbear/hoverbear.org
        git config gc.auto 0
        git fetch --depth 1 origin master
    - name: Checkout
      run:
        git checkout master
    - name: Install Zola
      run: sudo snap install --edge zola
    - name: Build site
      run: zola build --output-dir docs
    - name: Commit changes
      run: |
        git add docs
        git commit -s -m "Deploy ${GITHUB_SHA}."
    - name: Deploy site
      env:
        # Seems the token described in https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables doesn't work
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        git push "https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"